const theme = {
  heading: {
    h1: "text-5xl text-white",
    h2: "text-4xl text-white",
    h3: "text-3xl text-white",
    h4: "text-2xl text-white",
    h5: "text-xl text-white",
    h6: "text-lg text-white",
  },
  paragraph: "mb-3 text-white",
  list: {
    checklist: "PlaygroundEditorTheme__checklist",
    listitemChecked: "PlaygroundEditorTheme__listItemChecked",
    listitemUnchecked: "PlaygroundEditorTheme__listItemUnchecked",
    nested: {
      listitem: "editor-nested-listitem",
    },
    ol: "max-w-md space-y-1 list-decimal list-inside text-white",
    ul: "max-w-md space-y-1 list-disc list-inside text-white",
    listitem: "mx-4",
  },
  quote:
    "p-4 text-black my-4 border-s-4 border-gray-300 bg-gray-50 text-xl italic font-medium leading-relaxed mx-2",

  code: "PlaygroundEditorTheme__code",
  codeHighlight: {
    atrule: "PlaygroundEditorTheme__tokenAttr",
    attr: "PlaygroundEditorTheme__tokenAttr",
    boolean: "PlaygroundEditorTheme__tokenProperty",
    builtin: "PlaygroundEditorTheme__tokenSelector",
    cdata: "PlaygroundEditorTheme__tokenComment",
    char: "PlaygroundEditorTheme__tokenSelector",
    class: "PlaygroundEditorTheme__tokenFunction",
    "class-name": "PlaygroundEditorTheme__tokenFunction",
    comment: "PlaygroundEditorTheme__tokenComment",
    constant: "PlaygroundEditorTheme__tokenProperty",
    deleted: "PlaygroundEditorTheme__tokenProperty",
    doctype: "PlaygroundEditorTheme__tokenComment",
    entity: "PlaygroundEditorTheme__tokenOperator",
    function: "PlaygroundEditorTheme__tokenFunction",
    important: "PlaygroundEditorTheme__tokenVariable",
    inserted: "PlaygroundEditorTheme__tokenSelector",
    keyword: "PlaygroundEditorTheme__tokenAttr",
    namespace: "PlaygroundEditorTheme__tokenVariable",
    number: "PlaygroundEditorTheme__tokenProperty",
    operator: "PlaygroundEditorTheme__tokenOperator",
    prolog: "PlaygroundEditorTheme__tokenComment",
    property: "PlaygroundEditorTheme__tokenProperty",
    punctuation: "PlaygroundEditorTheme__tokenPunctuation",
    regex: "PlaygroundEditorTheme__tokenVariable",
    selector: "PlaygroundEditorTheme__tokenSelector",
    string: "PlaygroundEditorTheme__tokenSelector",
    symbol: "PlaygroundEditorTheme__tokenProperty",
    tag: "PlaygroundEditorTheme__tokenProperty",
    url: "PlaygroundEditorTheme__tokenOperator",
    variable: "PlaygroundEditorTheme__tokenVariable",
  },
  text: {
    bold: "font-bold",
    underline: "underline",
    strikethrough: "line-through",
    italic: "italic",
    highlight: "bg-yellow-200 p-1",
    code: "bg-gray-100 text-gray-800 p-2 rounded border border-gray-300",
    subscript: "subscript",
    superscript: "superscript",
  },
  link: "text-blue-500  hover:underline",
};
export default theme;
